# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/deckthehalls',
                'doc_host': 'https://audreyfeldroy.github.io',
                'git_url': 'https://github.com/audreyfeldroy/deckthehalls',
                'lib_path': 'deckthehalls'},
  'syms': {'deckthehalls.core': {'deckthehalls.core.foo': ('core.html#foo', 'deckthehalls/core.py')}}}
