# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/deckthehalls',
                'doc_host': 'https://audreyfeldroy.github.io',
                'git_url': 'https://github.com/audreyfeldroy/deckthehalls',
                'lib_path': 'deckthehalls'},
  'syms': { 'deckthehalls.core': { 'deckthehalls.core.NotebookToPygmentsFT': ('core.html#notebooktopygmentsft', 'deckthehalls/core.py'),
                                   'deckthehalls.core.NotebookToRandomPygmentsFT': ( 'core.html#notebooktorandompygmentsft',
                                                                                     'deckthehalls/core.py'),
                                   'deckthehalls.core.PythonToPygmentsFT': ('core.html#pythontopygmentsft', 'deckthehalls/core.py'),
                                   'deckthehalls.core.PythonToRandomPygmentsFT': ( 'core.html#pythontorandompygmentsft',
                                                                                   'deckthehalls/core.py'),
                                   'deckthehalls.core.get_code_cells': ('core.html#get_code_cells', 'deckthehalls/core.py'),
                                   'deckthehalls.core.index': ('core.html#index', 'deckthehalls/core.py'),
                                   'deckthehalls.core.is_code_cell': ('core.html#is_code_cell', 'deckthehalls/core.py'),
                                   'deckthehalls.core.randstyle': ('core.html#randstyle', 'deckthehalls/core.py')}}}
